[features]
seeds = false
skip-lint = false
[programs.localnet]
dca_integration = "5mrhiqFFXyfJMzAJc5vsEQ4cABRhfsP7MgSVgGQjfcrR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy-mainnet = "solana program deploy target/deploy/dca_integration.so --keypair ~/.config/solana/id.json --program-id target/deploy/dca_integration-keypair.json"

# ```sh
# anchor idl init --provider.cluster mainnet --filepath ./target/idl/dca_integration.json 5mrhiqFFXyfJMzAJc5vsEQ4cABRhfsP7MgSVgGQjfcrR --provider.wallet ~/.config/solana/id.json
# anchor idl upgrade --provider.cluster mainnet --filepath ./target/idl/dca_integration.json 5mrhiqFFXyfJMzAJc5vsEQ4cABRhfsP7MgSVgGQjfcrR --provider.wallet ~/.config/solana/id.json
# ```